spring:
  application:
    name: parcel-tracker
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:parceltracker;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled=true
    clean-on-validation-error=true
    locations=classpath:db/migration
    baseline-on-migrate=true
    validate-on-migrate=true

logging:
  level:
    com.hotel.parceltracker: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info